apps/login_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'registration'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout')
]

main/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_app.urls', namespace = 'loginspace')),
    url(r'^jobs/', include('apps.user_app.urls', namespace = 'userspace'))
]

apps/login_app/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile (r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def valid_registration(self, user_info, request):
        valid = True
        if not user_info['first_name'].isalpha():
            messages.warning(request, "First name must be all letters!")
            valid = False
        if len(user_info['first_name']) < 2:
            messages.warning(request, "First name must be at least 3 or more characters!")
            valid = False
        if not user_info['last_name'].isalpha():
            messages.warning(request, "Last name must be all letters!")
            valid = False
        if len(user_info['last_name']) < 2:
            messages.warning(request, "Last name must be at least 3 or more characters!")
            valid = False
        if not EMAIL_REGEX.match(user_info['email_address']):
            messages.warning(request, "Email is not valid!")
            valid = False
        if len(user_info['password']) < 7:
            messages.warning(request, "Password is too short!")
            valid = False
        if user_info['password'] != user_info['confirm_password']:
            messages.warning(request, "Passwords do not match!")
            valid = False
        if User.objects.filter(email = user_info['email_address']):
            messages.error(request, "The email is taken!")
            valid = False
        if valid == True:
            hashed = bcrypt.hashpw(user_info['password'].encode(), bcrypt.gensalt())
            User.objects.create(first_name = request.POST['first_name'], last_name = request.POST['last_name'], email = request.POST['email_address'], password = hashed)
        return valid

    def exisiting_user(self, user_info, request):
        valid = True
        if User.objects.filter(email = user_info['email_address']):
            hashed = User.objects.get(email = user_info['email_address']).password
            hashed = hashed.encode('utf-8')
            password = user_info['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
                valid = True
            else:
                messages.warning(request, "Incorrect password!")
                valid = False
        else:
            messages.warning(request, "Your email is not correct!")
            valid = False
        return valid

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    UserManager = UserManager()
    objects = models.Manager()

apps/login_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
    if 'first_name' not in request.session:
        return render(request, 'login_app/index.html')
    else:
        return render(request, 'user_app/home.html')

def register(request):
    if User.UserManager.valid_registration(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['user_id'] = user.id
        return redirect(reverse('userspace:home'))
    else:
        valid = False
        return redirect(reverse('loginspace:index'))

def login(request):
    if User.UserManager.exisiting_user(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['email_address'] = user.last_name
        request.session['user_id'] = user.id
        return redirect(reverse('userspace:home'))
    else:
        valid = False
        return redirect(reverse('loginspace:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('loginspace:index'))

apps/login_app/templates/login_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login & Registration</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        form {
            border: 1px solid black;
            border-radius: 5px;
            margin-right: 10px;
            margin-left: 10px;
            padding: 10px;
        }
    </style>
</head>

<body>
    <div class="container">

        <h1>Welcome!</h1>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <div class="row">
            <!-- register -->
            <form class="col" action="{% url 'loginspace:registration' %}" method="POST">
                <h3>Register</h3>
                <div class="form-group row">
                    {% csrf_token %}
                    <label for="first_name" class="col-sm-3 col-form-label">First Name:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" name="first_name" placeholder="first name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="last_name" class="col-sm-3 col-form-label">Last Name:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" name="last_name" placeholder="last name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="email_address" class="col-sm-3 col-form-label">Email:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" name="email_address" placeholder="email">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-3 col-form-label">Password:</label>
                    <div class="col-sm-9">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="confirm_password" class="col-sm-3 col-form-label">Confirm PW:</label>
                    <div class="col-sm-9">
                        <input type="password" class="form-control" name="confirm_password" placeholder="Password">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-form-label"></div>
                    <button type="submit" class="btn btn-success col-sm-2">Register</button>
                </div>
            </form>
            <!-- Login -->
            <form class="col" action="{% url 'loginspace:login' %}" method="POST">
                <h3>Login</h3>
                <div class="form-group row">
                    {% csrf_token %}
                    <label for="email_address" class="col-sm-3 col-form-label">Email:</label>
                    <div class="col-sm-9">
                        <input type="email" class="form-control" name="email_address" placeholder="email">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="password" class="col-sm-3 col-form-label">Password:</label>
                    <div class="col-sm-9">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-form-label"></div>
                    <button type="submit" class="btn btn-success col-sm-2">Login</button>
                </div>
            </form>
        </div>

        <!-- end of container -->
    </div>
</body>

</html>