apps/login_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^register$', views.register, name = 'registration'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout')
]

apps/user_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard$', views.home, name = "home"),
    url(r'^new$', views.add, name = "add"),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name = "destroy"),
    url(r'^granted/(?P<job_id>\d+)$', views.add_to_granteds, name = "granted"),
    url(r'^remove_granted/(?P<job_id>\d+)$', views.remove_granteds, name = "remove_granted"),
    url(r'^(?P<job_id>\d+)$', views.show, name = "show"),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name = "edit"),
    url(r'^update$', views.update, name = "update")

]

main/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_app.urls', namespace = 'loginspace')),
    url(r'^jobs/', include('apps.user_app.urls', namespace = 'userspace'))
]

apps/user_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_app.models import User

class Job(models.Model):
    title = models.CharField(max_length=45)
    desc = models.TextField(max_length=1000)
    location = models.CharField(max_length=45)
    posted_by = models.ForeignKey(User, related_name='user_jobs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Granted(models.Model):
    user = models.ForeignKey(User, related_name="user_granteds")
    job = models.ForeignKey(Job, related_name="job_granteds")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/user_app/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Job, Granted
from ..login_app.models import User
from django.db.models import Count
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models import Count

def home(request):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:

        all_jobs = Job.objects.all().order_by('-created_at')
        all_granteds = Granted.objects.filter(user_id = request.session['user_id']).order_by('-created_at')

        my_granted_jobs =[]
        granteds_list =[]
        for granted in all_granteds:
            granteds_list.append(granted.job.id)
            my_granted_jobs.append(granted.job)

        context = {
            'all_jobs': all_jobs,
            'granteds_list': granteds_list,
            'my_granted_jobs': my_granted_jobs,
            # 'all_granteds': all_granteds
        }
        return render(request, 'user_app/home.html', context)

def add(request):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    elif request.method == 'POST':
        title = request.POST.get('title')
        desc = request.POST.get('desc')
        location = request.POST.get('location')
        this_user = User.objects.get(id=request.session['user_id'])

        cate1 = request.POST.get("cate1")
        cate2 = request.POST.get("cate2")
        cate3 = request.POST.get("cate3")
        cate4 = request.POST.get("cate4")

        if len(title)<1 or len(desc)<1 or len(location)<1:
            messages.warning(request, 'no blanks!')
            return redirect('userspace:add')
        elif len(title)<3:
            messages.warning(request, 'title must be at least 3 characters')
            return redirect('userspace:add')
        elif len(desc)<5:
            messages.warning(request, 'description must be at least 5 characters')
            return redirect('userspace:add')
        elif len(location)<3:
            messages.warning(request, 'location must be at least 3 characters')
            return redirect('userspace:add')
        else:

            Job.objects.create(title = title, desc = desc, location = location, posted_by=this_user, cate1 = cate1, cate2 = cate2, cate3 = cate3, cate4 = cate4)

            return redirect(reverse('userspace:home'))
    return render(request, 'user_app/add.html')

def destroy(request, id):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:
        Job.objects.get(id=id).delete()
        return redirect(reverse('userspace:home'))

def add_to_granteds(request, job_id):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:
        this_user = User.objects.get(id=request.session['user_id'])
        this_job = Job.objects.get(id=job_id)

        Granted.objects.create(user=this_user, job=this_job)
        messages.success(request, 'Job has been assigned!')
        return redirect(reverse('userspace:home'))

def remove_granteds(request,job_id):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:
        user_id = request.session['user_id']
        this_job = Job.objects.get(id=job_id)
        this_user = User.objects.get(id=request.session['user_id'])

        this_granted = Granted.objects.filter(user=user_id,job=job_id)
        this_granted.delete()

        messages.success(request, 'Job removed from your jobs')

        return redirect(reverse('userspace:home'))

def show(request, job_id):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:
        jobs = Job.objects.filter(id = job_id)

        context = {
            'jobs': jobs,
            }

        return render(request, 'user_app/show.html', context)

def edit(request, job_id):
    if not 'first_name' in request.session:
        return redirect('loginspace:index')
    else:
        context={
            'jobs': Job.objects.get(id=job_id)
        }

        return render(request, 'user_app/edit.html', context)

def update(request):
    job = Job.objects.get(id=request.POST['id'])
    job.title = request.POST['title']
    job.desc = request.POST['desc']
    if len(job.title)<1 or len(job.desc)<1 or len(job.location)<1:
        messages.warning(request, 'No blanks!')
        return redirect(reverse('userspace:edit', kwargs = {"job_id" : request.POST['id']}))
    elif len(job.title)<3:
        messages.warning(request, 'title must be at least 3 characters')
        return redirect(reverse('userspace:edit', kwargs = {"job_id" : request.POST['id']}))
    elif len(job.desc)<5:
        messages.warning(request, 'description must be at least 5 characters')
        return redirect(reverse('userspace:edit', kwargs = {"job_id" : request.POST['id']}))
    elif len(job.location)<3:
        messages.warning(request, 'location must be at least 3 characters')
        return redirect(reverse('userspace:edit', kwargs = {"job_id" : request.POST['id']}))
    job.save()
    return redirect(reverse('userspace:home'))

apps/user_app/templates/user_app/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create new wishes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-9"></div>
            <div class="col">
                <a href="{% url 'userspace:home' %}">Home |</a>
                <a href="{% url 'loginspace:logout' %}">Logout</a>
            </div>
        </div>
        
        <div class="add-review">
            <h3>Hello {{request.session.first_name}}! Create a job! <span class="glyphicon glyphicon-book"></span></h3>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <form class="form-horizontal" action="{% url 'userspace:add' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="" class="col-sm-3 control-label">Title:</label>
                    <div class="col-sm-6">
                        <input type="text" name="title" class="form-control" placeholder="job">
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-3 control-label">Description</label>
                    <div class="col-sm-6">
                        <textarea class="form-control" name="desc" rows="3" placeholder="description"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-3 control-label">Location:</label>
                    <div class="col-sm-6">
                        <input type="text" name="location" class="form-control" placeholder="location">
                    </div>
                </div>

                <!-- selection -->
                <form class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-sm-2 pt-0">Category:</legend>
                        <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="cate1" value="Consultant">
                            <label class="form-check-label">
                            Consultant
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="cate2" id="gridRadios3" value="Accounting">
                            <label class="form-check-label">
                            Third disabled radio
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="cate3" id="gridRadios3" value="Sales">
                            <label class="form-check-label">
                            Third disabled radio
                            </label>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Others:</label>
                            <div class="col-sm-3">
                                <input type="text" name="cate4" class="form-control">
                            </div>
                        </div>
                    </div>
                </form>


    <!-- end of selection -->
                <br>
                <div class="form-group">
                    <div class="col-sm-offset-1 col-sm-6">
                        <button type="submit" class="btn btn-info">Submit</button>
                        <button class="btn btn-light"><a href="{% url 'userspace:home' %}">Cancel</a> </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

</html>

apps/user_app/templates/user_app/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit job</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-9"></div>
            <div class="col">
                <a href="{% url 'userspace:home' %}">Home |</a>
                <a href="{% url 'loginspace:logout' %}">Logout</a>
            </div>
        </div>
        
        <div class="add-review">
            <h3>Hello {{request.session.first_name}}! Let's edit your job! <span class="glyphicon glyphicon-book"></span></h3>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
            <form class="form-horizontal" action="{% url 'userspace:update' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{jobs.id}}">
                <div class="form-group">
                    <label for="title" class="col-sm-3 control-label">Title:</label>
                    <div class="col-sm-6">
                        <input type="text" name="title" class="form-control" value="{{jobs.title}}" placeholder="job">
                    </div>
                </div>

                <div class="form-group">
                    <label for="desc" class="col-sm-3 control-label">Description:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="desc" rows="3" value="{{jobs.desc}}" placeholder="description">
                    </div>
                </div>

                <div class="form-group">
                    <label for="location" class="col-sm-3 control-label">Location:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="location" value="{{jobs.location}}" placeholder="description">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-1 col-sm-6">
                        <button type="submit" class="btn btn-info">Submit</button>
                        <button class="btn btn-light"><a href="{% url 'userspace:home' %}">Cancel</a> </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</body>

</html>

apps/user_app/templates/user_app/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <!-- top -->
        <div class="row">
            <div class="col">
                <h2>Hello, {{request.session.first_name}}!</h2>
            </div>
            <div class="col-4"></div>
            <div class="col">
                <a href="{% url 'loginspace:logout' %}">Logout </a>
                <button type="button" class="btn btn-outline-warning"><a href="{% url 'userspace:add' %}">New job!</a></button>
            </div>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        <!-- mid -->
        <div class="row">
            <h4>Everyone's jobs:</h4>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Job</th>
                        <th scope="col">Location</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in all_jobs %}
                        {% if not i.id in granteds_list %}
                        <tr>
                            <td>{{i.title}}</td>
                            <td>{{i.location}}</td>
                            <td>
                                <a href="/jobs/{{i.id}}">View |</a>
                                {% if i.posted_by.id == request.session.user_id %}
                                    <a href="/jobs/destroy/{{i.id}}">Remove |</a>
                                    <a href="/jobs/edit/{{i.id}}">Edit |</a>
                                {% else %}
                                {% endif %}
                                <a href="/jobs/granted/{{i.id}}">Add</a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- right -->
        <div class="row">
            <h4>{{request.session.first_name}}'s jobs:</h4>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Job</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in my_granted_jobs %}
                    <tr>
                        <td>{{i.title}}</td>
                        <td>
                            <a href="/jobs/{{i.id}}">View | </a>
                            <a href="/jobs/destroy/{{i.id}}">Done | </a>
                            <a href="/jobs/remove_granted/{{i.id}}">Give up</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</body>

</html>

apps/user_app/templates/user_app/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jobs Info</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="container">

        <div class="row">
            <div class="col-9"></div>
            <div class="col">
                <a href="{% url 'userspace:home' %}">Home |</a>
                <a href="{% url 'loginspace:logout' %}">Logout</a>
            </div>
        </div>
        <h1>Hello {{request.session.first_name}}! There are job's details!</h1>
        {% for i in jobs%}
            <h3>{{i.title}}</h3>
            <p>{{i.desc}}</p>
            <p>Location: {{i.location}}</p>
            <p>Posted by: {{i.posted_by.first_name}}</p>
            <p>Posted on: {{i.created_at}}</p>
            <p>Categories: {{i.cate1}} {{i.cate2}} {{i.cate3}} {{i.cate4}}</p>
        {%endfor%}

    </div>
</body>
</html>